### ISSUE TITLE
devcontainer postStartCommand

### ISSUE THREAD

**Issue by rm98** [polaris-slo-cloud/polaris#57]
The `postStartCommand` of the devcontainer seems to be wrong.
[Link to line.](https://github.com/polaris-slo-cloud/polaris/blob/master/.devcontainer/devcontainer.json#L43)

It uses `kubectl apply -k`, but it does not seem to be setup as a [Kubernetes kustomization directory](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) because it lacks the `kustomization.yaml`.

This is probably related to 
* [this commit that remove the go code, and also the `kustomization.yaml` in `go/config/crd`](https://github.com/polaris-slo-cloud/polaris/commit/8d0faa900bae9ddb9b646ae233cacfdb2afd4b85#diff-de0e2a0613af51a34b1b161790ba87475ac98fceee545023865ea299767d486a)
* [and this commit that updates the devcontainer](https://github.com/polaris-slo-cloud/polaris/commit/9794d92f4932228e56b35e6d21a1ef3a59dcf91e)

I am unsure what the right kind of action is, the comment in the line above the offending line also hints that this may be obsolete sometime/already.

**Comment by tommazzo89** [comment]
Thank you for pointing this out! I've just corrected the command to `kubectl apply -f`.
